In [4]:
import pandas as pd

df = pd.read_csv('/figure-4.csv')

print(df)

             Category Marker      Category     Sex  Number Percentage
0         Mode of employment     Full-time  Female  137830        49%
1         Mode of employment     Full-time    Male  145665        51%
2         Mode of employment     Full-time   Other     440         0%
3         Mode of employment     Part-time  Female   87210        66%
4         Mode of employment     Part-time    Male   44585        34%
5         Mode of employment     Part-time   Other     240         0%
6   Academic contract marker      Academic  Female  105440        47%
7   Academic contract marker      Academic    Male  118695        53%
8   Academic contract marker      Academic   Other     390         0%
9   Academic contract marker  Non-academic  Female  119600        62%
10  Academic contract marker  Non-academic    Male   71550        37%
11  Academic contract marker  Non-academic   Other     290         0%

In [22]:

#mean
print(df['Number'].mean())

#median
print(df['Number'].median())

#mode
print(df['Number'].mode())

#sum
print(sum(df['Number']))

69327.91666666667
79380.0
0        240
1        290
2        390
3        440
4      44585
5      71550
6      87210
7     105440
8     118695
9     119600
10    137830
11    145665
Name: Number, dtype: int64
831935

In [23]:
display(df.iloc[:, :4])

             Category Marker      Category     Sex  Number
0         Mode of employment     Full-time  Female  137830
1         Mode of employment     Full-time    Male  145665
2         Mode of employment     Full-time   Other     440
3         Mode of employment     Part-time  Female   87210
4         Mode of employment     Part-time    Male   44585
5         Mode of employment     Part-time   Other     240
6   Academic contract marker      Academic  Female  105440
7   Academic contract marker      Academic    Male  118695
8   Academic contract marker      Academic   Other     390
9   Academic contract marker  Non-academic  Female  119600
10  Academic contract marker  Non-academic    Male   71550
11  Academic contract marker  Non-academic   Other     290